# Generated by Django 4.1 on 2022-08-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=2000)),
                ('message', models.TextField(max_length=50000)),
                ('slug', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
