# Generated by Django 4.1 on 2022-08-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blogcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
